"""change priority to string

Revision ID: 213c959aa7c6
Revises: 2c613b714c67
Create Date: 2026-01-19 14:31:57.423660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213c959aa7c6'
down_revision = '2c613b714c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
