"""add due date to todo

Revision ID: 72baf3628278
Revises: 213c959aa7c6
Create Date: 2026-01-20 19:22:03.034848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72baf3628278'
down_revision = '213c959aa7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
